import { Escola, Profile, Profissional, Turma, Aluno, PDI, Oficio, DocumentoAluno, AuditLogItem, EstudoDeCaso, PEIOfficial } from '../types';

export const INITIAL_ESCOLAS: Escola[] = [
  // 1. ALTAMIRA (7 Escolas)
  {
    id: 'e1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-ALT-001',
    nome: 'EEE. M. Polivalente',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Maria do Carmo Santos',
    cargo_responsavel: 'Professor(a) de AEE: Francilene de Menezes Silva',
    endereco: 'Av. Brigadeiro Eduardo Gomes, s/n - Esplanada do Xingu, Altamira - PA',
    telefone: '(93) 99108-0977',
    email: 'francilene.msilva@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 56,
    qtd_alunos_sem_laudo: 5,
    detalhe_diagnosticos: 'TEA: 22, Deficiência Física: 2, TDAH: 14, DI: 2, Deficiência Visual: 2, Microcefalia: 2, Síndrome de Down: 2, Deficiência Auditiva: 2, Altas Habilidades/Superdotação: 2, Baixa Visão: 3, Retardo Mental: 3',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI',
    observacoes_regionais: 'A principal dificuldade refere-se à insuficiência de cuidadores para atender a demanda dos estudantes público da Educação Especial.',
    ativa: true,
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'e2222222-2222-2222-2222-222222222222',
    codigo: 'ESC-ALT-002',
    nome: 'EEE. M. Dairce Pedrosa',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Maria Antônia Silva',
    cargo_responsavel: 'Professor(a) de AEE: Cláudia Andrade da Silva',
    endereco: 'Rua Magalhães Barata, 450 - Centro, Altamira - PA',
    telefone: '(93) 99144-4387',
    email: 'claudia.silva58712@escola.seduc.pa.gov.br',
    modalidade: 'INTEGRAL',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 13,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 11, Deficiência Intelectual: 3, Deficiência Física: 1',
    dificuldades_docentes: 'Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'Atendimento integral. Possui duas cuidadoras contratadas para apoio matutino e vespertino.',
    ativa: true,
    created_at: '2025-01-12T09:30:00Z',
  },
  {
    id: 'b1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-ALT-003',
    nome: 'EE Bartolomeu de Moraes',
    municipio: 'Altamira',
    diretor_nome: 'Prof. Carlos Alberto Lima',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Andréia Cláudia Gehring Rocha',
    endereco: 'Rua Sete de Setembro, 820 - Sudam I, Altamira - PA',
    telefone: '(93) 98111-2538',
    email: 'andreia.rocha@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'inativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 1,
    qtd_alunos_sem_laudo: 3,
    detalhe_diagnosticos: 'Deficiência Intelectual: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'O aluno necessita de profissional de apoio devido à baixa mobilidade de locomoção pelos corredores e banheiro.',
    ativa: true,
    created_at: '2025-01-15T11:00:00Z',
  },
  {
    id: 'b1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-ALT-004',
    nome: 'EEE. M. Profª Ducilla Almeida',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Maria do Socorro Pinheiro',
    cargo_responsavel: 'Professor(a) de AEE: Darcilene de Oliveira Miléo',
    endereco: 'Av. João Pessoa, 1100 - Sudam II, Altamira - PA',
    telefone: '(93) 99172-1029',
    email: 'darcilene.oliveira@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 16,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 8, Deficiência Intelectual: 7, Deficiência Física: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas',
    observacoes_regionais: 'Dois alunos matriculados no 1º ano ainda não frequentam por falta de professores auxiliares e cuidadores.',
    ativa: true,
    created_at: '2025-01-18T10:00:00Z',
  },
  {
    id: 'd5555555-5555-5555-5555-555555555555',
    codigo: 'ESC-ALT-005',
    nome: 'EEE. M. Getúlio Vargas',
    municipio: 'Altamira',
    diretor_nome: 'Prof. Antônio Marcos Vieira',
    cargo_responsavel: 'Professor(a) de AEE: Lucilene da Silva Vaz',
    endereco: 'Rua Acesso 1, s/n - São Sebastião, Altamira - PA',
    telefone: '(93) 99214-8490',
    email: 'lucilene.vaz@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 14,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 5, Deficiência Intelectual: 7, Deficiência Auditiva Unilateral: 1, Deficiência Visual/Miopia: 1',
    dificuldades_docentes: 'Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'Necessidade urgente de cuidador auxiliar para o estudante Gabriel Silva Gomes com deficiências múltiplas.',
    ativa: true,
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'c2222222-2222-2222-2222-222222222222',
    codigo: 'ESC-ALT-006',
    nome: 'EE. Rural de Altamira',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Flaviele Santos Ferreira',
    cargo_responsavel: 'Coordenação Escolar: Flaviele Santos Ferreira',
    endereco: 'Comunidades Rurais / Localidade Sol Nascente, Altamira - PA',
    telefone: '(91) 98639-6686',
    email: 'flaviele.ferreira4474@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'parcial',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Deficiência Intelectual: 1, Autismo Clássico: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental, Falta de material didático adaptado',
    observacoes_regionais: 'Opera em prédios cedidos pelo município. Única possibilidade própria em Sol Nascente não tem iluminação/ventilação adequada.',
    ativa: true,
    created_at: '2025-01-22T08:00:00Z',
  },
  {
    id: 'e7777777-7777-7777-7777-777777777777',
    codigo: 'ESC-ALT-007',
    nome: 'EEE. M. Profª Odila de Souza',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Marta Roberta da Silva Rodrigues',
    cargo_responsavel: 'Gestão Escolar: Marta Roberta da Silva Rodrigues',
    endereco: 'Travessa Dezesseis, 310 - Jardim Independente I, Altamira - PA',
    telefone: '(93) 98103-4511',
    email: 'marta.rodrigues@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 26,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 9, DI: 4, Baixa Visão: 3, TDAH: 5, Psicose Infantil: 3, Transtorno Mental: 1, Retardo Mental: 1, Epilepsia: 1, Desgaste Cartilagem: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI, Articulação com saúde para laudos',
    observacoes_regionais: 'Urgência na lotação de docente para implantação de sala de AEE e de cuidadores adicionais para suporte em sala regular.',
    ativa: true,
    created_at: '2025-01-25T08:00:00Z',
  },

  // 2. BRASIL NOVO (2 Escolas)
  {
    id: 'a0eef48e-7252-4930-a00a-fe41b2d416a8',
    codigo: 'ESC-BN-001',
    nome: 'EE. Rural de Brasil Novo',
    municipio: 'Brasil Novo',
    diretor_nome: 'Manoel da Silva Araújo',
    cargo_responsavel: 'Diretor(a) Escolar: Manoel da Silva Araújo',
    endereco: 'Vila Carlos Pena Filho, Rodovia Transamazônica Km 46, Brasil Novo - PA',
    telefone: '(93) 99119-0742',
    email: 'manoel.araujo@escola.seduc.pa.gov.br',
    modalidade: 'SOME',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 5,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Deficiência Intelectual: 3, DI + TDAH: 1, Deficiência Auditiva: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental, Falta de material didático adaptado',
    observacoes_regionais: 'Carência extrema de cuidadores nas comunidades do SOME. Processos seletivos precisam alcançar candidatos residentes no campo.',
    ativa: true,
    created_at: '2025-01-20T10:15:00Z',
  },
  {
    id: 'b1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-BN-002',
    nome: 'EEE. M. Brasil Novo',
    municipio: 'Brasil Novo',
    diretor_nome: 'Prof. João Bosco Tavares',
    cargo_responsavel: 'Professor(a) de AEE: Rozinete Francisca Rezende',
    endereco: 'Av. Castelo Branco, 520 - Centro, Brasil Novo - PA',
    telefone: '(93) 99169-5921',
    email: 'rozinete.rezende@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 21,
    qtd_alunos_sem_laudo: 6,
    detalhe_diagnosticos: 'TEA CID 11.602: 8, DI Grupo F70-F79: 11, Baixa Visão: 3, Surdez: 2, TDAH: 5, Cegueira Monocular: 2, TOD: 3, Baixa Audição: 2, Dislexia: 1, Cegueira: 1',
    dificuldades_docentes: 'Adaptação de avaliações, Manejo comportamental, Articulação com saúde, Falta de material didático adaptado',
    observacoes_regionais: 'Possui cuidadores contratados porém com quantitativo reduzido para a demanda de atendimento individualizado.',
    ativa: true,
    created_at: '2025-01-22T10:00:00Z',
  },

  // 3. VITÓRIA DO XINGU (2 Escolas)
  {
    id: 'c1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-VTX-001',
    nome: 'EEE. M. Padre Eurico',
    municipio: 'Vitória do Xingu',
    diretor_nome: 'Maria Ferreira Duarte',
    cargo_responsavel: 'Diretor(a) Escolar: Maria Ferreira Duarte',
    endereco: 'Av. Manoel Félix, 320 - Centro, Vitória do Xingu - PA',
    telefone: '(93) 99128-7533',
    email: 'maria.fduarte@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 24,
    qtd_alunos_sem_laudo: 5,
    detalhe_diagnosticos: 'TEA: 12, DI: 13, TDI: 2, TDAH: 4, Deficiência Auditiva: 2, Deficiência Visual: 3, Deficiência Física: 3',
    dificuldades_docentes: 'Preenchimento do PDI, Falta de material didático adaptado',
    observacoes_regionais: 'Unidade central sem sala de recursos multifuncionais ativa e sem cuidadores contratados para os 24 alunos com laudo.',
    ativa: true,
    created_at: '2025-01-25T16:00:00Z',
  },
  {
    id: 'c2222222-2222-2222-2222-222222222222',
    codigo: 'ESC-VTX-002',
    nome: 'EE. Rural de Vitória do Xingu',
    municipio: 'Vitória do Xingu',
    diretor_nome: 'Prof. Valmir do Nascimento Sousa',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Valmir do Nascimento Sousa',
    endereco: 'Comunidade Belo Monte do Pontal, Zona Rural, Vitória do Xingu - PA',
    telefone: '(93) 99122-5193',
    email: 'valmir.sousa@escola.seduc.pa.gov.br',
    modalidade: 'SOME/CEMEP',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 3,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 2, Deficiência Intelectual: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI, Falta de material didático adaptado',
    observacoes_regionais: 'Atendimento SOME/CEMEP. Acompanhante Ildiany Gonçalves atuando na turma M3TNMI01.',
    ativa: true,
    created_at: '2025-01-26T08:00:00Z',
  },

  // 4. PORTO DE MOZ (3 Escolas)
  {
    id: '23c0cc9b-f655-4e7d-a1d6-00dcbc5bad5d',
    codigo: 'ESC-PDM-001',
    nome: 'EEE. M. Dom Pedro I',
    municipio: 'Porto de Moz',
    diretor_nome: 'Prof. Raimundo Nonato Castro',
    cargo_responsavel: 'Coordenação Escolar: Benilda da Silva Guerra',
    endereco: 'Rua Lauro Sodré, 210 - Centro, Porto de Moz - PA',
    telefone: '(93) 98416-7946',
    email: 'benilda.sguerra@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 9,
    qtd_alunos_sem_laudo: 4,
    detalhe_diagnosticos: 'TEA: 7, Deficiência Intelectual: 4, Síndrome de Down: 1, Surdez: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas',
    observacoes_regionais: 'Necessidade prioritária de intérprete de LIBRAS para acompanhar estudante na sala regular; risco de desmotivação e evasão.',
    ativa: true,
    created_at: '2025-01-27T08:00:00Z',
  },
  {
    id: 'd1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-PDM-002',
    nome: 'EE. Rural de Porto de Moz',
    municipio: 'Porto de Moz',
    diretor_nome: 'Cleoson da Silva Aranha',
    cargo_responsavel: 'Diretor(a) Escolar: Cleoson da Silva Aranha',
    endereco: 'Vilas Ribeirinhas e Ilhas do Rio Xingu, Porto de Moz - PA',
    telefone: '(93) 98431-5756',
    email: 'cleoson.aranha@escola.seduc.pa.gov.br',
    modalidade: 'CEMEP',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 9,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 2, Deficiência Auditiva: 1, Deficiência Física: 3, Deficiência Visual: 2, Deficiência Intelectual: 1',
    dificuldades_docentes: 'Sem espaço físico próprio, carência integral de profissionais e materiais adaptados',
    observacoes_regionais: 'No momento a escola sequer conta com espaço escolar físico próprio. Faz-se urgente infraestrutura física e equipe técnica de apoio.',
    ativa: true,
    created_at: '2025-01-28T08:00:00Z',
  },
  {
    id: 'd2222222-2222-2222-2222-222222222222',
    codigo: 'ESC-PDM-003',
    nome: 'EEE. M. José Alfredo Hage',
    municipio: 'Porto de Moz',
    diretor_nome: 'Profª. Maria do Perpétuo Socorro',
    cargo_responsavel: 'Professor(a) de AEE: Marla Cristina de Lima Costa',
    endereco: 'Rua Castelo Branco, 140 - Alto Bonito, Porto de Moz - PA',
    telefone: '(93) 98115-1204',
    email: 'marla.costa45290@escola.seduc.pa.gov.br',
    modalidade: 'INTEGRAL',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 13,
    qtd_alunos_sem_laudo: 1,
    detalhe_diagnosticos: 'Deficiência Física: 3, Surdez: 1, Deficiência Múltipla: 1, Baixa Visão: 1, Deficiência Intelectual: 7',
    dificuldades_docentes: 'Adaptação de atividades, Articulação com saúde, Falta de material adaptado',
    observacoes_regionais: 'Atendimento integral com 1 estagiária apoiadora. Necessita ampliação de cuidadores efetivos.',
    ativa: true,
    created_at: '2025-01-29T08:00:00Z',
  },

  // 5. SENADOR JOSÉ PORFÍRIO (2 Escolas)
  {
    id: 'd3333333-3333-3333-3333-333333333333',
    codigo: 'ESC-SJP-001',
    nome: 'EE. Rural de Senador José Porfírio',
    municipio: 'Senador José Porfírio',
    diretor_nome: 'Leandro Patrick de Oliveira Pena',
    cargo_responsavel: 'Diretor(a) Escolar: Leandro Patrick de Oliveira Pena',
    endereco: 'Comunidades Rurais da Volta Grande do Xingu, Senador José Porfírio - PA',
    telefone: '(93) 99158-5700',
    email: 'leandro.pena@escola.seduc.pa.gov.br',
    modalidade: 'SOME',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 1,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Deficiência Intelectual: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades e provas',
    observacoes_regionais: 'Sem sala de AEE e sem profissionais de apoio para o estudante.',
    ativa: true,
    created_at: '2025-01-30T08:00:00Z',
  },
  {
    id: 'd4444444-4444-4444-4444-444444444444',
    codigo: 'ESC-SJP-002',
    nome: 'EEE. M. Rosa Alvarez Rebelo',
    municipio: 'Senador José Porfírio',
    diretor_nome: 'Nixon Klauberg Macedo Calado',
    cargo_responsavel: 'Diretor(a) Escolar: Nixon Klauberg Macedo Calado',
    endereco: 'Rua Principal, s/n - Centro, Senador José Porfírio - PA',
    telefone: '(93) 99172-8747',
    email: 'nixon.calado@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'inativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'CID Q90.9 (Síndrome de Down): 1, CID F71/G40/G80 (DI, Epilepsia, Paralisia Cerebral): 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental',
    observacoes_regionais: 'A escola não possui nenhum profissional de AEE nem cuidador. Sem atendimento efetivo.',
    ativa: true,
    created_at: '2025-01-31T08:00:00Z',
  },

  // 6. MEDICILÂNDIA (2 Escolas)
  {
    id: 'd5555555-5555-5555-5555-555555555555',
    codigo: 'ESC-MED-001',
    nome: 'EEE. M. Francisca Gomes',
    municipio: 'Medicilândia',
    diretor_nome: 'Angelina Tereza',
    cargo_responsavel: 'Diretor(a) Escolar: Angelina Tereza',
    endereco: 'Av. dos Cacauicultores, 800 - Centro, Medicilândia - PA',
    telefone: '(93) 99112-5219',
    email: 'angelina.tereza28@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'inativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 14,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 9, Deficiência Intelectual: 3, TDAH: 1, Doença Degenerativa: 1',
    dificuldades_docentes: 'Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'Falta de assistente educacional na sala regular e profissional especialista para o SAEE.',
    ativa: true,
    created_at: '2025-01-22T14:20:00Z',
  },
  {
    id: 'd6666666-6666-6666-6666-666666666666',
    codigo: 'ESC-MED-002',
    nome: 'EE. Rural de Medicilândia',
    municipio: 'Medicilândia',
    diretor_nome: 'Valdoneis Francisco da Silva',
    cargo_responsavel: 'Diretor(a) Escolar: Valdoneis Francisco da Silva',
    endereco: 'Vilas Vicinais da Rodovia Transamazônica Km 90 a 120, Medicilândia - PA',
    telefone: '(93) 99217-8127',
    email: 'valdoneis.silva3377@escola.seduc.pa.gov.br',
    modalidade: 'CEMEP',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'parcial',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 12,
    qtd_alunos_sem_laudo: 4,
    detalhe_diagnosticos: 'TEA: 6, Deficiência Intelectual: 6',
    dificuldades_docentes: 'Preenchimento do PDI, Manejo comportamental, Falta de material adaptado',
    observacoes_regionais: 'Possuímos alunos graves que dependem inteiramente de cuidadores e não temos nenhum profissional contratado.',
    ativa: true,
    created_at: '2025-02-01T08:00:00Z',
  },

  // 7. ANAPU (3 Escolas)
  {
    id: 'd7777777-7777-7777-7777-777777777777',
    codigo: 'ESC-ANP-001',
    nome: 'EE. Rural de Anapu',
    municipio: 'Anapu',
    diretor_nome: 'Profª. Ana Keline Gonzaga',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Ana Keline da Silva Gonzaga Aguiar',
    endereco: 'Comunidades Rurais Km 70 ao 110, Anapu - PA',
    telefone: '(91) 98435-2911',
    email: 'ana.gonzaga@escola.seduc.pa.gov.br',
    modalidade: 'SOME/CEMEP',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 2, Deficiência Auditiva: 1, Deficiências Múltiplas: 1',
    dificuldades_docentes: 'Adaptação de atividades, Preenchimento do PDI, Articulação de laudos com saúde',
    observacoes_regionais: 'Atendimento leigo em SOME/CEMEP. Não há tradutor de LIBRAS nem cuidador.',
    ativa: true,
    created_at: '2025-02-02T08:00:00Z',
  },
  {
    id: 'd8888888-8888-8888-8888-888888888888',
    codigo: 'ESC-ANP-002',
    nome: 'EEE. M. Santa Clara',
    municipio: 'Anapu',
    diretor_nome: 'Giuliano Souza Guzzo',
    cargo_responsavel: 'Diretor(a) Escolar: Giuliano Souza Guzzo',
    endereco: 'Rua Santa Luzia, 150 - Centro, Anapu - PA',
    telefone: '(91) 99124-1449',
    email: 'giuliano.guzzo@escola.seduc.pa.gov.br',
    modalidade: 'INTEGRAL',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'ok',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Síndrome de Down com Cardiopatia (Q90.9, Q25.0), Hidrocefalia (G91.0)',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental',
    observacoes_regionais: 'Atendimento em tempo integral. Acompanhante Andreia Machado atuando nas turmas de 1º e 2º ano.',
    ativa: true,
    created_at: '2025-02-03T08:00:00Z',
  },
  {
    id: 'd9999999-9999-9999-9999-999999999999',
    codigo: 'ESC-ANP-003',
    nome: 'EEE. M. Maria José Santana',
    municipio: 'Anapu',
    diretor_nome: 'Prof. Marcos Rogério Mendes',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Alysson Mateus Marques Andrade',
    endereco: 'Av. Brasil, 400 - Bela Vista, Anapu - PA',
    telefone: '(93) 99122-0294',
    email: 'alysson.andrade@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 6,
    qtd_alunos_sem_laudo: 1,
    detalhe_diagnosticos: 'TEA (6A02): 1, Transtorno Linguagem (F80): 1, Atraso Neuropsicomotor (F84/F72): 1, Autismo e TDAH (F840/F900): 1, Dificuldade Aprendizado: 1, Retardo Mental Leve: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI',
    observacoes_regionais: 'Temos professora de AEE ativa mas não temos nenhum acompanhante escolar contratado.',
    ativa: true,
    created_at: '2025-02-04T08:00:00Z',
  },

  // 8. URUARÁ (2 Escolas)
  {
    id: 'daaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    codigo: 'ESC-URU-001',
    nome: 'EE. Rural de Uruará',
    municipio: 'Uruará',
    diretor_nome: 'Wanderson do Sacramento Moraes',
    cargo_responsavel: 'Diretor(a) Escolar: Wanderson do Sacramento Moraes',
    endereco: 'Comunidades Rurais Km 140 ao 180, Uruará - PA',
    telefone: '(93) 99139-1822',
    email: 'wanderson.moraes@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: false,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 3,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TDAH (F90), Transtornos do Desenvolvimento (F83, F81)',
    dificuldades_docentes: 'Adaptação de atividades, Preenchimento do PDI, Manejo comportamental, Falta de material adaptado',
    observacoes_regionais: 'Sem profissionais contratados na área da Educação Especial.',
    ativa: true,
    created_at: '2025-02-05T08:00:00Z',
  },
  {
    id: 'e717707d-2dac-4f43-a458-1d623b4df6fb',
    codigo: 'ESC-URU-002',
    nome: 'EEE. M. Melvin Jones',
    municipio: 'Uruará',
    diretor_nome: 'Profª. Maria Aparecida Silva',
    cargo_responsavel: 'Professor(a) de AEE: Laurilene Matos da Silva',
    endereco: 'Rua Principal, 300 - Centro, Uruará - PA',
    telefone: '(93) 99147-4950',
    email: 'laurilene.msilva@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'parcial',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 46,
    qtd_alunos_sem_laudo: 35,
    detalhe_diagnosticos: 'TEA: 23, Deficiência Intelectual: 13, TDAH: 6, Deficiência Física: 4',
    dificuldades_docentes: 'Elaboração e adaptação de atividades, Preenchimento do PDI, Manejo comportamental, Falta de material didático adaptado',
    observacoes_regionais: 'Demanda de 81 estudantes (46 laudos e 35 em investigação). Profª Laurilene atende EEMAE01 e EETAE01 porém não há cuidadores.',
    ativa: true,
    created_at: '2025-02-06T08:00:00Z',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'daad1701-0680-420b-af89-5c8e6dc4a1bf',
    nome: 'Prof. Antonio Vieira Bispo',
    email: 'antonio.bispo@escola.seduc.pa.gov.br',
    cargo: 'Coordenador Pedagógico / Diretor Regional',
    papel: 'nucleo_diretor',
    escola_id: null,
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-01T08:00:00Z',
    ultimo_acesso: new Date().toISOString(),
  }
];

// Dados operacionais limpos para início do zero
export const INITIAL_PROFISSIONAIS: Profissional[] = [];
export const INITIAL_TURMAS: Turma[] = [];
export const INITIAL_ALUNOS: Aluno[] = [];
export const INITIAL_PDIS: PDI[] = [];
export const INITIAL_OFICIOS: Oficio[] = [];
export const INITIAL_DOCUMENTOS: DocumentoAluno[] = [];
export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [];
export const INITIAL_ESTUDOS_DE_CASO: EstudoDeCaso[] = [];
export const INITIAL_PEIS: PEIOfficial[] = [];
