import { Escola, Profile, Profissional, Turma, Aluno, PDI, Oficio, DocumentoAluno, AuditLogItem, EstudoDeCaso, PEIOfficial } from '../types';

export const INITIAL_ESCOLAS: Escola[] = [
  // 1. ALTAMIRA (7 Escolas)
  {
    id: 'e1111111-1111-1111-1111-111111111111',
    codigo: 'ESC-ALT-001',
    nome: 'EEE. M. Polivalente',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Maria do Carmo Santos',
    cargo_responsavel: 'Professor(a) de AEE: Francilene de Menezes Silva',
    endereco: 'Av. Brigadeiro Eduardo Gomes, s/n - Esplanada do Xingu, Altamira - PA',
    telefone: '(93) 99108-0977',
    email: 'francilene.msilva@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 56,
    qtd_alunos_sem_laudo: 5,
    detalhe_diagnosticos: 'TEA: 22, Deficiência Física: 2, TDAH: 14, DI: 2, Deficiência Visual: 2, Microcefalia: 2, Síndrome de Down: 2, Deficiência Auditiva: 2, Altas Habilidades/Superdotação: 2, Baixa Visão: 3, Retardo Mental: 3',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI',
    observacoes_regionais: 'A principal dificuldade refere-se à insuficiência de cuidadores para atender a demanda dos estudantes público da Educação Especial.',
    ativa: true,
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'e2222222-2222-2222-2222-222222222222',
    codigo: 'ESC-ALT-002',
    nome: 'EEE. M. Dairce Pedrosa',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Maria Antônia Silva',
    cargo_responsavel: 'Professor(a) de AEE: Cláudia Andrade da Silva',
    endereco: 'Rua Magalhães Barata, 450 - Centro, Altamira - PA',
    telefone: '(93) 99144-4387',
    email: 'claudia.silva58712@escola.seduc.pa.gov.br',
    modalidade: 'INTEGRAL',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 13,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 11, Deficiência Intelectual: 3, Deficiência Física: 1',
    dificuldades_docentes: 'Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'Atendimento integral. Possui duas cuidadoras contratadas para apoio matutino e vespertino.',
    ativa: true,
    created_at: '2025-01-12T09:30:00Z',
  },
  {
    id: 'e-alt-bartolomeu',
    codigo: 'ESC-ALT-003',
    nome: 'EE Bartolomeu de Moraes',
    municipio: 'Altamira',
    diretor_nome: 'Prof. Carlos Alberto Lima',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Andréia Cláudia Gehring Rocha',
    endereco: 'Rua Sete de Setembro, 820 - Sudam I, Altamira - PA',
    telefone: '(93) 98111-2538',
    email: 'andreia.rocha@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'inativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 1,
    qtd_alunos_sem_laudo: 3,
    detalhe_diagnosticos: 'Deficiência Intelectual: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'O aluno necessita de profissional de apoio devido à baixa mobilidade de locomoção pelos corredores e banheiro.',
    ativa: true,
    created_at: '2025-01-15T11:00:00Z',
  },
  {
    id: 'e3333333-3333-3333-3333-333333333333',
    codigo: 'ESC-ALT-004',
    nome: 'EEE. M. Profª Ducilla Almeida',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Maria do Socorro Pinheiro',
    cargo_responsavel: 'Professor(a) de AEE: Darcilene de Oliveira Miléo',
    endereco: 'Av. João Pessoa, 1100 - Sudam II, Altamira - PA',
    telefone: '(93) 99172-1029',
    email: 'darcilene.oliveira@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 16,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 8, Deficiência Intelectual: 7, Deficiência Física: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas',
    observacoes_regionais: 'Dois alunos matriculados no 1º ano ainda não frequentam por falta de professores auxiliares e cuidadores.',
    ativa: true,
    created_at: '2025-01-18T10:00:00Z',
  },
  {
    id: 'e-alt-getulio',
    codigo: 'ESC-ALT-005',
    nome: 'EEE. M. Getúlio Vargas',
    municipio: 'Altamira',
    diretor_nome: 'Prof. Antônio Marcos Vieira',
    cargo_responsavel: 'Professor(a) de AEE: Lucilene da Silva Vaz',
    endereco: 'Rua Acesso 1, s/n - São Sebastião, Altamira - PA',
    telefone: '(93) 99214-8490',
    email: 'lucilene.vaz@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 14,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 5, Deficiência Intelectual: 7, Deficiência Auditiva Unilateral: 1, Deficiência Visual/Miopia: 1',
    dificuldades_docentes: 'Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'Necessidade urgente de cuidador auxiliar para o estudante Gabriel Silva Gomes com deficiências múltiplas.',
    ativa: true,
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'e-alt-rural',
    codigo: 'ESC-ALT-006',
    nome: 'EE. Rural de Altamira',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Flaviele Santos Ferreira',
    cargo_responsavel: 'Coordenação Escolar: Flaviele Santos Ferreira',
    endereco: 'Comunidades Rurais / Localidade Sol Nascente, Altamira - PA',
    telefone: '(91) 98639-6686',
    email: 'flaviele.ferreira4474@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'parcial',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Deficiência Intelectual: 1, Autismo Clássico: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental, Falta de material didático adaptado',
    observacoes_regionais: 'Opera em prédios cedidos pelo município. Única possibilidade própria em Sol Nascente não tem iluminação/ventilação adequada.',
    ativa: true,
    created_at: '2025-01-22T08:00:00Z',
  },
  {
    id: 'e-alt-odila',
    codigo: 'ESC-ALT-007',
    nome: 'EEE. M. Profª Odila de Souza',
    municipio: 'Altamira',
    diretor_nome: 'Profª. Marta Roberta da Silva Rodrigues',
    cargo_responsavel: 'Gestão Escolar: Marta Roberta da Silva Rodrigues',
    endereco: 'Travessa Dezesseis, 310 - Jardim Independente I, Altamira - PA',
    telefone: '(93) 98103-4511',
    email: 'marta.rodrigues@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 26,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 9, DI: 4, Baixa Visão: 3, TDAH: 5, Psicose Infantil: 3, Transtorno Mental: 1, Retardo Mental: 1, Epilepsia: 1, Desgaste Cartilagem: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI, Articulação com saúde para laudos',
    observacoes_regionais: 'Urgência na lotação de docente para implantação de sala de AEE e de cuidadores adicionais para suporte em sala regular.',
    ativa: true,
    created_at: '2025-01-25T08:00:00Z',
  },

  // 2. BRASIL NOVO (2 Escolas)
  {
    id: 'e-bn-rural',
    codigo: 'ESC-BN-001',
    nome: 'EE. Rural de Brasil Novo',
    municipio: 'Brasil Novo',
    diretor_nome: 'Manoel da Silva Araújo',
    cargo_responsavel: 'Diretor(a) Escolar: Manoel da Silva Araújo',
    endereco: 'Vila Carlos Pena Filho, Rodovia Transamazônica Km 46, Brasil Novo - PA',
    telefone: '(93) 99119-0742',
    email: 'manoel.araujo@escola.seduc.pa.gov.br',
    modalidade: 'SOME',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 5,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Deficiência Intelectual: 3, DI + TDAH: 1, Deficiência Auditiva: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental, Falta de material didático adaptado',
    observacoes_regionais: 'Carência extrema de cuidadores nas comunidades do SOME. Processos seletivos precisam alcançar candidatos residentes no campo.',
    ativa: true,
    created_at: '2025-01-20T10:15:00Z',
  },
  {
    id: 'e4444444-4444-4444-4444-444444444444',
    codigo: 'ESC-BN-002',
    nome: 'EEE. M. Brasil Novo',
    municipio: 'Brasil Novo',
    diretor_nome: 'Prof. João Bosco Tavares',
    cargo_responsavel: 'Professor(a) de AEE: Rozinete Francisca Rezende',
    endereco: 'Av. Castelo Branco, 520 - Centro, Brasil Novo - PA',
    telefone: '(93) 99169-5921',
    email: 'rozinete.rezende@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 21,
    qtd_alunos_sem_laudo: 6,
    detalhe_diagnosticos: 'TEA CID 11.602: 8, DI Grupo F70-F79: 11, Baixa Visão: 3, Surdez: 2, TDAH: 5, Cegueira Monocular: 2, TOD: 3, Baixa Audição: 2, Dislexia: 1, Cegueira: 1',
    dificuldades_docentes: 'Adaptação de avaliações, Manejo comportamental, Articulação com saúde, Falta de material didático adaptado',
    observacoes_regionais: 'Possui cuidadores contratados porém com quantitativo reduzido para a demanda de atendimento individualizado.',
    ativa: true,
    created_at: '2025-01-22T10:00:00Z',
  },

  // 3. VITÓRIA DO XINGU (2 Escolas)
  {
    id: 'e-vtx-eurico',
    codigo: 'ESC-VTX-001',
    nome: 'EEE. M. Padre Eurico',
    municipio: 'Vitória do Xingu',
    diretor_nome: 'Maria Ferreira Duarte',
    cargo_responsavel: 'Diretor(a) Escolar: Maria Ferreira Duarte',
    endereco: 'Av. Manoel Félix, 320 - Centro, Vitória do Xingu - PA',
    telefone: '(93) 99128-7533',
    email: 'maria.fduarte@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 24,
    qtd_alunos_sem_laudo: 5,
    detalhe_diagnosticos: 'TEA: 12, DI: 13, TDI: 2, TDAH: 4, Deficiência Auditiva: 2, Deficiência Visual: 3, Deficiência Física: 3',
    dificuldades_docentes: 'Preenchimento do PDI, Falta de material didático adaptado',
    observacoes_regionais: 'Unidade central sem sala de recursos multifuncionais ativa e sem cuidadores contratados para os 24 alunos com laudo.',
    ativa: true,
    created_at: '2025-01-25T16:00:00Z',
  },
  {
    id: 'e6666666-6666-6666-6666-666666666666',
    codigo: 'ESC-VTX-002',
    nome: 'EE. Rural de Vitória do Xingu',
    municipio: 'Vitória do Xingu',
    diretor_nome: 'Prof. Valmir do Nascimento Sousa',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Valmir do Nascimento Sousa',
    endereco: 'Comunidade Belo Monte do Pontal, Zona Rural, Vitória do Xingu - PA',
    telefone: '(93) 99122-5193',
    email: 'valmir.sousa@escola.seduc.pa.gov.br',
    modalidade: 'SOME/CEMEP',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 3,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 2, Deficiência Intelectual: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI, Falta de material didático adaptado',
    observacoes_regionais: 'Atendimento SOME/CEMEP. Acompanhante Ildiany Gonçalves atuando na turma M3TNMI01.',
    ativa: true,
    created_at: '2025-01-26T08:00:00Z',
  },

  // 4. PORTO DE MOZ (3 Escolas)
  {
    id: 'e-pdm-pedro',
    codigo: 'ESC-PDM-001',
    nome: 'EEE. M. Dom Pedro I',
    municipio: 'Porto de Moz',
    diretor_nome: 'Prof. Raimundo Nonato Castro',
    cargo_responsavel: 'Coordenação Escolar: Benilda da Silva Guerra',
    endereco: 'Rua Lauro Sodré, 210 - Centro, Porto de Moz - PA',
    telefone: '(93) 98416-7946',
    email: 'benilda.sguerra@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 9,
    qtd_alunos_sem_laudo: 4,
    detalhe_diagnosticos: 'TEA: 7, Deficiência Intelectual: 4, Síndrome de Down: 1, Surdez: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas',
    observacoes_regionais: 'Necessidade prioritária de intérprete de LIBRAS para acompanhar estudante na sala regular; risco de desmotivação e evasão.',
    ativa: true,
    created_at: '2025-01-27T08:00:00Z',
  },
  {
    id: 'e-pdm-rural',
    codigo: 'ESC-PDM-002',
    nome: 'EE. Rural de Porto de Moz',
    municipio: 'Porto de Moz',
    diretor_nome: 'Cleoson da Silva Aranha',
    cargo_responsavel: 'Diretor(a) Escolar: Cleoson da Silva Aranha',
    endereco: 'Vilas Ribeirinhas e Ilhas do Rio Xingu, Porto de Moz - PA',
    telefone: '(93) 98431-5756',
    email: 'cleoson.aranha@escola.seduc.pa.gov.br',
    modalidade: 'CEMEP',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 9,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 2, Deficiência Auditiva: 1, Deficiência Física: 3, Deficiência Visual: 2, Deficiência Intelectual: 1',
    dificuldades_docentes: 'Sem espaço físico próprio, carência integral de profissionais e materiais adaptados',
    observacoes_regionais: 'No momento a escola sequer conta com espaço escolar físico próprio. Faz-se urgente infraestrutura física e equipe técnica de apoio.',
    ativa: true,
    created_at: '2025-01-28T08:00:00Z',
  },
  {
    id: 'e-pdm-hage',
    codigo: 'ESC-PDM-003',
    nome: 'EEE. M. José Alfredo Hage',
    municipio: 'Porto de Moz',
    diretor_nome: 'Profª. Maria do Perpétuo Socorro',
    cargo_responsavel: 'Professor(a) de AEE: Marla Cristina de Lima Costa',
    endereco: 'Rua Castelo Branco, 140 - Alto Bonito, Porto de Moz - PA',
    telefone: '(93) 98115-1204',
    email: 'marla.costa45290@escola.seduc.pa.gov.br',
    modalidade: 'INTEGRAL',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'parcial',
    qtd_alunos_laudo: 13,
    qtd_alunos_sem_laudo: 1,
    detalhe_diagnosticos: 'Deficiência Física: 3, Surdez: 1, Deficiência Múltipla: 1, Baixa Visão: 1, Deficiência Intelectual: 7',
    dificuldades_docentes: 'Adaptação de atividades, Articulação com saúde, Falta de material adaptado',
    observacoes_regionais: 'Atendimento integral com 1 estagiária apoiadora. Necessita ampliação de cuidadores efetivos.',
    ativa: true,
    created_at: '2025-01-29T08:00:00Z',
  },

  // 5. SENADOR JOSÉ PORFÍRIO (2 Escolas)
  {
    id: 'e-sjp-rural',
    codigo: 'ESC-SJP-001',
    nome: 'EE. Rural de Senador José Porfírio',
    municipio: 'Senador José Porfírio',
    diretor_nome: 'Leandro Patrick de Oliveira Pena',
    cargo_responsavel: 'Diretor(a) Escolar: Leandro Patrick de Oliveira Pena',
    endereco: 'Comunidades Rurais da Volta Grande do Xingu, Senador José Porfírio - PA',
    telefone: '(93) 99158-5700',
    email: 'leandro.pena@escola.seduc.pa.gov.br',
    modalidade: 'SOME',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 1,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Deficiência Intelectual: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades e provas',
    observacoes_regionais: 'Sem sala de AEE e sem profissionais de apoio para o estudante.',
    ativa: true,
    created_at: '2025-01-30T08:00:00Z',
  },
  {
    id: 'e-sjp-rebelo',
    codigo: 'ESC-SJP-002',
    nome: 'EEE. M. Rosa Alvarez Rebelo',
    municipio: 'Senador José Porfírio',
    diretor_nome: 'Nixon Klauberg Macedo Calado',
    cargo_responsavel: 'Diretor(a) Escolar: Nixon Klauberg Macedo Calado',
    endereco: 'Rua Principal, s/n - Centro, Senador José Porfírio - PA',
    telefone: '(93) 99172-8747',
    email: 'nixon.calado@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'inativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'CID Q90.9 (Síndrome de Down): 1, CID F71/G40/G80 (DI, Epilepsia, Paralisia Cerebral): 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental',
    observacoes_regionais: 'A escola não possui nenhum profissional de AEE nem cuidador. Sem atendimento efetivo.',
    ativa: true,
    created_at: '2025-01-31T08:00:00Z',
  },

  // 6. MEDICILÂNDIA (2 Escolas)
  {
    id: 'e5555555-5555-5555-5555-555555555555',
    codigo: 'ESC-MED-001',
    nome: 'EEE. M. Francisca Gomes',
    municipio: 'Medicilândia',
    diretor_nome: 'Angelina Tereza',
    cargo_responsavel: 'Diretor(a) Escolar: Angelina Tereza',
    endereco: 'Av. dos Cacauicultores, 800 - Centro, Medicilândia - PA',
    telefone: '(93) 99112-5219',
    email: 'angelina.tereza28@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'inativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 14,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'TEA: 9, Deficiência Intelectual: 3, TDAH: 1, Doença Degenerativa: 1',
    dificuldades_docentes: 'Manejo de comportamentos em sala de aula',
    observacoes_regionais: 'Falta de assistente educacional na sala regular e profissional especialista para o SAEE.',
    ativa: true,
    created_at: '2025-01-22T14:20:00Z',
  },
  {
    id: 'e-med-rural',
    codigo: 'ESC-MED-002',
    nome: 'EE. Rural de Medicilândia',
    municipio: 'Medicilândia',
    diretor_nome: 'Valdoneis Francisco da Silva',
    cargo_responsavel: 'Diretor(a) Escolar: Valdoneis Francisco da Silva',
    endereco: 'Vilas Vicinais da Rodovia Transamazônica Km 90 a 120, Medicilândia - PA',
    telefone: '(93) 99217-8127',
    email: 'valdoneis.silva3377@escola.seduc.pa.gov.br',
    modalidade: 'CEMEP',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'parcial',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 12,
    qtd_alunos_sem_laudo: 4,
    detalhe_diagnosticos: 'TEA: 6, Deficiência Intelectual: 6',
    dificuldades_docentes: 'Preenchimento do PDI, Manejo comportamental, Falta de material adaptado',
    observacoes_regionais: 'Possuímos alunos graves que dependem inteiramente de cuidadores e não temos nenhum profissional contratado.',
    ativa: true,
    created_at: '2025-02-01T08:00:00Z',
  },

  // 7. ANAPU (3 Escolas)
  {
    id: 'e-anp-rural',
    codigo: 'ESC-ANP-001',
    nome: 'EE. Rural de Anapu',
    municipio: 'Anapu',
    diretor_nome: 'Profª. Ana Keline Gonzaga',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Ana Keline da Silva Gonzaga Aguiar',
    endereco: 'Comunidades Rurais Km 70 ao 110, Anapu - PA',
    telefone: '(91) 98435-2911',
    email: 'ana.gonzaga@escola.seduc.pa.gov.br',
    modalidade: 'SOME/CEMEP',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: true,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TEA: 2, Deficiência Auditiva: 1, Deficiências Múltiplas: 1',
    dificuldades_docentes: 'Adaptação de atividades, Preenchimento do PDI, Articulação de laudos com saúde',
    observacoes_regionais: 'Atendimento leigo em SOME/CEMEP. Não há tradutor de LIBRAS nem cuidador.',
    ativa: true,
    created_at: '2025-02-02T08:00:00Z',
  },
  {
    id: 'e-anp-santaclara',
    codigo: 'ESC-ANP-002',
    nome: 'EEE. M. Santa Clara',
    municipio: 'Anapu',
    diretor_nome: 'Giuliano Souza Guzzo',
    cargo_responsavel: 'Diretor(a) Escolar: Giuliano Souza Guzzo',
    endereco: 'Rua Santa Luzia, 150 - Centro, Anapu - PA',
    telefone: '(91) 99124-1449',
    email: 'giuliano.guzzo@escola.seduc.pa.gov.br',
    modalidade: 'INTEGRAL',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'todos',
    situacao_cuidadores: 'ok',
    qtd_alunos_laudo: 2,
    qtd_alunos_sem_laudo: 0,
    detalhe_diagnosticos: 'Síndrome de Down com Cardiopatia (Q90.9, Q25.0), Hidrocefalia (G91.0)',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Manejo comportamental',
    observacoes_regionais: 'Atendimento em tempo integral. Acompanhante Andreia Machado atuando nas turmas de 1º e 2º ano.',
    ativa: true,
    created_at: '2025-02-03T08:00:00Z',
  },
  {
    id: 'e-anp-santana',
    codigo: 'ESC-ANP-003',
    nome: 'EEE. M. Maria José Santana',
    municipio: 'Anapu',
    diretor_nome: 'Prof. Marcos Rogério Mendes',
    cargo_responsavel: 'Coordenador(a) Pedagógico(a): Alysson Mateus Marques Andrade',
    endereco: 'Av. Brasil, 400 - Bela Vista, Anapu - PA',
    telefone: '(93) 99122-0294',
    email: 'alysson.andrade@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 6,
    qtd_alunos_sem_laudo: 1,
    detalhe_diagnosticos: 'TEA (6A02): 1, Transtorno Linguagem (F80): 1, Atraso Neuropsicomotor (F84/F72): 1, Autismo e TDAH (F840/F900): 1, Dificuldade Aprendizado: 1, Retardo Mental Leve: 1',
    dificuldades_docentes: 'Elaboração e adaptação de atividades/provas, Preenchimento do PDI',
    observacoes_regionais: 'Temos professora de AEE ativa mas não temos nenhum acompanhante escolar contratado.',
    ativa: true,
    created_at: '2025-02-04T08:00:00Z',
  },

  // 8. URUARÁ (2 Escolas)
  {
    id: 'e-uru-rural',
    codigo: 'ESC-URU-001',
    nome: 'EE. Rural de Uruará',
    municipio: 'Uruará',
    diretor_nome: 'Wanderson do Sacramento Moraes',
    cargo_responsavel: 'Diretor(a) Escolar: Wanderson do Sacramento Moraes',
    endereco: 'Comunidades Rurais Km 140 ao 180, Uruará - PA',
    telefone: '(93) 99139-1822',
    email: 'wanderson.moraes@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'nao_possui',
    possui_srm: false,
    atendimento_some: false,
    pdi_status_geral: 'nenhum',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 3,
    qtd_alunos_sem_laudo: 2,
    detalhe_diagnosticos: 'TDAH (F90), Transtornos do Desenvolvimento (F83, F81)',
    dificuldades_docentes: 'Adaptação de atividades, Preenchimento do PDI, Manejo comportamental, Falta de material adaptado',
    observacoes_regionais: 'Sem profissionais contratados na área da Educação Especial.',
    ativa: true,
    created_at: '2025-02-05T08:00:00Z',
  },
  {
    id: 'e-uru-melvin',
    codigo: 'ESC-URU-002',
    nome: 'EEE. M. Melvin Jones',
    municipio: 'Uruará',
    diretor_nome: 'Profª. Maria Aparecida Silva',
    cargo_responsavel: 'Professor(a) de AEE: Laurilene Matos da Silva',
    endereco: 'Rua Principal, 300 - Centro, Uruará - PA',
    telefone: '(93) 99147-4950',
    email: 'laurilene.msilva@escola.seduc.pa.gov.br',
    modalidade: 'REGULAR',
    srm_status: 'ativa',
    possui_srm: true,
    atendimento_some: false,
    pdi_status_geral: 'parcial',
    situacao_cuidadores: 'nenhum',
    qtd_alunos_laudo: 46,
    qtd_alunos_sem_laudo: 35,
    detalhe_diagnosticos: 'TEA: 23, Deficiência Intelectual: 13, TDAH: 6, Deficiência Física: 4',
    dificuldades_docentes: 'Elaboração e adaptação de atividades, Preenchimento do PDI, Manejo comportamental, Falta de material didático adaptado',
    observacoes_regionais: 'Demanda de 81 estudantes (46 laudos e 35 em investigação). Profª Laurilene atende EEMAE01 e EETAE01 porém não há cuidadores.',
    ativa: true,
    created_at: '2025-02-06T08:00:00Z',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'u1111111-1111-1111-1111-111111111111',
    nome: 'Prof. Dr. Valter Mendonça',
    email: 'valter.mendonca@seduc.pa.gov.br',
    cargo: 'Diretor do Núcleo de Educação Especial / DRE Regional',
    papel: 'nucleo_diretor',
    escola_id: null,
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-01T08:00:00Z',
    ultimo_acesso: '2026-09-21T09:15:00Z',
  },
  {
    id: 'u2222222-2222-2222-2222-222222222222',
    nome: 'Regina Helena Vasconcelos',
    email: 'regina.vasconcelos@seduc.pa.gov.br',
    cargo: 'Técnica de Referência em Ed. Especial',
    papel: 'nucleo_tecnico',
    escola_id: null,
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-05T08:30:00Z',
    ultimo_acesso: '2026-09-21T08:50:00Z',
  },
  {
    id: 'u3333333-3333-3333-3333-333333333333',
    nome: 'Profª. Maria do Carmo Santos',
    email: 'maria.santos@seduc.pa.gov.br',
    cargo: 'Diretora Escolar',
    papel: 'diretor_escola',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-10T09:00:00Z',
    ultimo_acesso: '2026-09-20T17:30:00Z',
  },
  {
    id: 'u4444444-4444-4444-4444-444444444444',
    nome: 'Marcos Aurélio Lima',
    email: 'marcos.lima@seduc.pa.gov.br',
    cargo: 'Secretário Escolar',
    papel: 'secretaria_escola',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-11T10:00:00Z',
    ultimo_acesso: '2026-09-21T07:45:00Z',
  },
  {
    id: 'u-dir-bn',
    nome: 'Manoel da Silva Araújo',
    email: 'manoel.araujo@escola.seduc.pa.gov.br',
    cargo: 'Diretor Escolar',
    papel: 'diretor_escola',
    escola_id: 'e-bn-rural',
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-15T08:00:00Z',
    ultimo_acesso: '2026-09-21T08:00:00Z',
  },
  {
    id: 'u-dir-pdm',
    nome: 'Cleoson da Silva Aranha',
    email: 'cleoson.aranha@escola.seduc.pa.gov.br',
    cargo: 'Diretor Escolar',
    papel: 'diretor_escola',
    escola_id: 'e-pdm-rural',
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-18T08:00:00Z',
    ultimo_acesso: '2026-09-21T08:00:00Z',
  },
  {
    id: 'u-dir-uruara',
    nome: 'Laurilene Matos da Silva',
    email: 'laurilene.msilva@escola.seduc.pa.gov.br',
    cargo: 'Professora de AEE',
    papel: 'secretaria_escola',
    escola_id: 'e-uru-melvin',
    ativo: true,
    senha: 'seduc@dre2026',
    created_at: '2025-01-20T08:00:00Z',
    ultimo_acesso: '2026-09-21T08:00:00Z',
  },
  {
    id: 'u-antonio-bispo',
    nome: 'Prof. Antonio Vieira Bispo',
    email: 'antonio.bispo@escola.seduc.pa.gov.br',
    cargo: 'Coordenador Pedagógico / Diretor Escolar',
    papel: 'diretor_escola',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    ativo: true,
    senha: 'Bispo@2026',
    created_at: '2025-01-22T08:00:00Z',
    ultimo_acesso: '2026-09-21T10:00:00Z',
  },
];

export const INITIAL_PROFISSIONAIS: Profissional[] = [
  // Altamira - Polivalente
  {
    id: 'p1111111-1111-1111-1111-111111111111',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    nome: 'Francilene de Menezes Silva',
    tipo: 'professor_aee',
    documento_ou_matricula: 'MAT-584920-SEDUC',
    telefone: '(93) 99108-0977',
    vinculo_contratual: 'Efetivo SEDUC',
    ativo: true,
    created_at: '2025-02-01T08:00:00Z',
  },
  {
    id: 'p-poli-luana',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    nome: 'Luana Azevedo Gonçalves de Souza',
    tipo: 'acompanhante',
    documento_ou_matricula: '5993747',
    telefone: '(93) 98411-2299',
    vinculo_contratual: 'Contrato 20/10/2025 a 31/12/2026',
    ativo: true,
    created_at: '2025-02-01T08:30:00Z',
  },
  {
    id: 'p-poli-elizeneia',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    nome: 'Elizeneia Lopes Ulian',
    tipo: 'acompanhante',
    documento_ou_matricula: '5994017',
    telefone: '(93) 99144-8822',
    vinculo_contratual: 'Contrato 27/10/2025 a 27/10/2026',
    ativo: true,
    created_at: '2025-02-01T09:00:00Z',
  },

  // Altamira - Dairce Pedrosa
  {
    id: 'p-dairce-claudia',
    escola_id: 'e2222222-2222-2222-2222-222222222222',
    nome: 'Cláudia Andrade da Silva',
    tipo: 'professor_aee',
    documento_ou_matricula: '58712-SEDUC',
    telefone: '(93) 99144-4387',
    vinculo_contratual: 'Efetivo SEDUC',
    ativo: true,
    created_at: '2025-02-01T08:00:00Z',
  },
  {
    id: 'p-dairce-aldineia',
    escola_id: 'e2222222-2222-2222-2222-222222222222',
    nome: 'Aldineia Alves Silva Luz',
    tipo: 'acompanhante',
    documento_ou_matricula: '599187-9',
    telefone: '(93) 99177-3311',
    vinculo_contratual: 'Contrato 01/05/2025 a 01/08/2028',
    ativo: true,
    created_at: '2025-02-01T08:30:00Z',
  },
  {
    id: 'p-dairce-aline',
    escola_id: 'e2222222-2222-2222-2222-222222222222',
    nome: 'Aline Nascimento Araújo Feitosa',
    tipo: 'acompanhante',
    documento_ou_matricula: '5958710-2',
    telefone: '(93) 98112-9900',
    vinculo_contratual: 'Contrato 01/05/2025 a 01/08/2028',
    ativo: true,
    created_at: '2025-02-01T09:00:00Z',
  },

  // Altamira - Profª Ducilla Almeida
  {
    id: 'p-ducilla-darcilene',
    escola_id: 'e3333333-3333-3333-3333-333333333333',
    nome: 'Darcilene de Oliveira Miléo',
    tipo: 'professor_aee',
    documento_ou_matricula: '5086124',
    telefone: '(93) 99172-1029',
    vinculo_contratual: 'Efetivo SEDUC (2 Turmas)',
    ativo: true,
    created_at: '2025-02-05T08:00:00Z',
  },

  // Altamira - Getúlio Vargas
  {
    id: 'p-getulio-lucilene',
    escola_id: 'e-alt-getulio',
    nome: 'Lucilene da Silva Vaz',
    tipo: 'professor_aee',
    documento_ou_matricula: 'MAT-492103',
    telefone: '(93) 99214-8490',
    vinculo_contratual: 'Efetivo SEDUC',
    ativo: true,
    created_at: '2025-02-05T08:00:00Z',
  },
  {
    id: 'p-getulio-henya',
    escola_id: 'e-alt-getulio',
    nome: 'Henya de Oliveira Farina',
    tipo: 'acompanhante',
    documento_ou_matricula: '5992800',
    telefone: '(93) 99155-7766',
    vinculo_contratual: 'Contrato 24/09/2025',
    ativo: true,
    created_at: '2025-02-05T08:30:00Z',
  },

  // Altamira - Odila de Souza
  {
    id: 'p-odila-geovane',
    escola_id: 'e-alt-odila',
    nome: 'Geovane Bezerra da Silva',
    tipo: 'acompanhante',
    documento_ou_matricula: '5992375',
    telefone: '(93) 98400-1122',
    vinculo_contratual: 'Contrato SEDUC',
    ativo: true,
    created_at: '2025-02-08T08:00:00Z',
  },

  // Brasil Novo - Sede
  {
    id: 'p-bn-rozinete',
    escola_id: 'e4444444-4444-4444-4444-444444444444',
    nome: 'Rozinete Francisca Rezende',
    tipo: 'professor_aee',
    documento_ou_matricula: 'MAT-784019',
    telefone: '(93) 99169-5921',
    vinculo_contratual: 'Efetivo SEDUC',
    ativo: true,
    created_at: '2025-02-08T08:00:00Z',
  },
  {
    id: 'p-bn-dania',
    escola_id: 'e4444444-4444-4444-4444-444444444444',
    nome: 'Dania Cristina Lopes',
    tipo: 'acompanhante',
    documento_ou_matricula: '5973703-2',
    telefone: '(93) 99188-4455',
    vinculo_contratual: 'Contrato até 08/2027',
    ativo: true,
    created_at: '2025-02-08T08:30:00Z',
  },
  {
    id: 'p-bn-sara',
    escola_id: 'e4444444-4444-4444-4444-444444444444',
    nome: 'Sara Talita Pereira',
    tipo: 'acompanhante',
    documento_ou_matricula: '5991877-1',
    telefone: '(93) 99144-2233',
    vinculo_contratual: 'Contrato até 08/2027',
    ativo: true,
    created_at: '2025-02-08T08:45:00Z',
  },

  // Porto de Moz - Dom Pedro I
  {
    id: 'p-pdm-josiane',
    escola_id: 'e-pdm-pedro',
    nome: 'Josiane Pontes de Souza',
    tipo: 'acompanhante',
    documento_ou_matricula: '55587962/2',
    telefone: '(93) 98416-7946',
    vinculo_contratual: 'Contrato 22/06/2026',
    ativo: true,
    created_at: '2025-02-10T08:00:00Z',
  },

  // Porto de Moz - José Alfredo Hage
  {
    id: 'p-hage-marla',
    escola_id: 'e-pdm-hage',
    nome: 'Marla Cristina de Lima Costa',
    tipo: 'professor_aee',
    documento_ou_matricula: '45290-SEDUC',
    telefone: '(93) 98115-1204',
    vinculo_contratual: 'Efetivo SEDUC',
    ativo: true,
    created_at: '2025-02-10T08:30:00Z',
  },
  {
    id: 'p-hage-marcela',
    escola_id: 'e-pdm-hage',
    nome: 'Marcela Riza Conceição Marques',
    tipo: 'acompanhante',
    documento_ou_matricula: '4221900-1',
    telefone: '(93) 98115-5544',
    vinculo_contratual: 'Estagiária Apoiadora (22/06/2026)',
    ativo: true,
    created_at: '2025-02-10T09:00:00Z',
  },

  // Vitória do Xingu - Rural
  {
    id: 'p-vtx-ildiany',
    escola_id: 'e6666666-6666-6666-6666-666666666666',
    nome: 'Ildiany Gonçalves Borges',
    tipo: 'acompanhante',
    documento_ou_matricula: '5982161/1',
    telefone: '(93) 99122-5193',
    vinculo_contratual: 'Contrato 21/05/2024',
    ativo: true,
    created_at: '2025-02-12T08:00:00Z',
  },

  // Anapu - Santa Clara
  {
    id: 'p-anp-andreia',
    escola_id: 'e-anp-santaclara',
    nome: 'Andreia Machado de Almeida',
    tipo: 'acompanhante',
    documento_ou_matricula: '7566050/1',
    telefone: '(91) 99124-1449',
    vinculo_contratual: 'Contrato 27/01/2025',
    ativo: true,
    created_at: '2025-02-14T08:00:00Z',
  },

  // Uruará - Melvin Jones
  {
    id: 'p-uru-laurilene',
    escola_id: 'e-uru-melvin',
    nome: 'Laurilene Matos da Silva',
    tipo: 'professor_aee',
    documento_ou_matricula: '7566396-1',
    telefone: '(93) 99147-4950',
    vinculo_contratual: 'Contrato 28/01/2025 (EEMAE01 / EETAE01)',
    ativo: true,
    created_at: '2025-02-15T08:00:00Z',
  },
];

export const INITIAL_TURMAS: Turma[] = [
  {
    id: 't1111111-1111-1111-1111-111111111111',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    codigo: 'M3TNM04',
    nome: '3ª Série M04 - Médio Tarde',
    turno: 'Tarde',
    ano_letivo: 2026,
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 't-dairce-01',
    escola_id: 'e2222222-2222-2222-2222-222222222222',
    codigo: 'EEMAE01',
    nome: 'AEE Manhã Integral',
    turno: 'Integral',
    ano_letivo: 2026,
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 't-bart-01',
    escola_id: 'e-alt-bartolomeu',
    codigo: '901-M',
    nome: '9º Ano Regular - Manhã',
    turno: 'Manhã',
    ano_letivo: 2026,
    created_at: '2026-01-16T08:00:00Z',
  },
  {
    id: 't-bn-01',
    escola_id: 'e4444444-4444-4444-4444-444444444444',
    codigo: 'M2TNM02',
    nome: '2ª Série Regular - Tarde',
    turno: 'Tarde',
    ano_letivo: 2026,
    created_at: '2026-01-18T08:00:00Z',
  },
  {
    id: 't-bn-rural-01',
    escola_id: 'e-bn-rural',
    codigo: 'SOME-BN01',
    nome: 'Turma SOME Campo 01',
    turno: 'Manhã',
    ano_letivo: 2026,
    created_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 't-vtx-01',
    escola_id: 'e-vtx-eurico',
    codigo: 'VTX-101',
    nome: '1º Ano Médio Regular',
    turno: 'Manhã',
    ano_letivo: 2026,
    created_at: '2026-01-22T08:00:00Z',
  },
  {
    id: 't-pdm-01',
    escola_id: 'e-pdm-pedro',
    codigo: 'PDM-201',
    nome: '2ª Série Médio Regular',
    turno: 'Tarde',
    ano_letivo: 2026,
    created_at: '2026-01-24T08:00:00Z',
  },
  {
    id: 't-uru-01',
    escola_id: 'e-uru-melvin',
    codigo: 'EEMAE01',
    nome: 'AEE Manhã Regular',
    turno: 'Manhã',
    ano_letivo: 2026,
    created_at: '2026-01-25T08:00:00Z',
  },
];

export const INITIAL_ALUNOS: Aluno[] = [
  // 1. Gabriel Souza (Polivalente - Altamira) -> Atendimento Regularizado (Verde)
  {
    id: 'a1111111-1111-1111-1111-111111111111',
    codigo: 'ALU-2026-001',
    nome: 'Gabriel Souza Nascimento',
    data_nascimento: '2009-04-12',
    sexo: 'M',
    endereco: 'Rua Sete de Setembro, 340 - Altamira',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    turma_id: 't1111111-1111-1111-1111-111111111111',
    ciclo: 2,
    serie: '3ª Série EM',
    situacao_doc: 'com_laudo',
    cid: 'F84.0',
    numero_processo: 'PROC-2025/1192-SEDUC',
    contrato_acompanhante: true,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: 'p1111111-1111-1111-1111-111111111111',
    acompanhante_id: 'p-poli-luana',
    observacoes: 'TEA com atendimento na Sala de Recursos e apoio em sala comum.',
    ativo: true,
    created_by: 'u4444444-4444-4444-4444-444444444444',
    updated_by: 'u3333333-3333-3333-3333-333333333333',
    created_at: '2026-02-05T09:00:00Z',
    updated_at: '2026-02-15T14:20:00Z',
  },

  // 2. Larissa Vitória (Polivalente - Altamira) -> Falta Acompanhante (Laranja)
  {
    id: 'a2222222-2222-2222-2222-222222222222',
    codigo: 'ALU-2026-002',
    nome: 'Larissa Vitória de Oliveira',
    data_nascimento: '2010-09-28',
    sexo: 'F',
    endereco: 'Travessa 10, nº 88 - Altamira',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    turma_id: 't1111111-1111-1111-1111-111111111111',
    ciclo: 2,
    serie: '3ª Série EM',
    situacao_doc: 'com_laudo',
    cid: 'G80',
    numero_processo: 'PROC-2025/0843-SEDUC',
    contrato_acompanhante: false,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: 'p1111111-1111-1111-1111-111111111111',
    acompanhante_id: null,
    observacoes: 'Paralisia cerebral com comprometimento motor. Aguarda cuidador.',
    ativo: true,
    created_by: 'u4444444-4444-4444-4444-444444444444',
    updated_by: 'u4444444-4444-4444-4444-444444444444',
    created_at: '2026-02-06T10:30:00Z',
    updated_at: '2026-02-06T10:30:00Z',
  },

  // 3. Davi Lucca (EE Rural de Brasil Novo) -> Sem Nenhum Profissional (Vermelho)
  {
    id: 'a3333333-3333-3333-3333-333333333333',
    codigo: 'ALU-2026-003',
    nome: 'Davi Lucca Ribeiro Ramos',
    data_nascimento: '2011-03-15',
    sexo: 'M',
    endereco: 'Vila Carlos Pena Filho, Km 46 - Brasil Novo',
    escola_id: 'e-bn-rural',
    turma_id: 't-bn-rural-01',
    ciclo: 1,
    serie: '9º Ano SOME',
    situacao_doc: 'com_laudo',
    cid: 'F70',
    numero_processo: 'PROC-2026/0122-SEDUC',
    contrato_acompanhante: false,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: null,
    acompanhante_id: null,
    observacoes: 'Estudante da comunidade rural sem professor de AEE e sem cuidador na turma do SOME.',
    ativo: true,
    created_by: 'u1111111-1111-1111-1111-111111111111',
    updated_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-08T11:00:00Z',
    updated_at: '2026-02-18T16:00:00Z',
  },

  // 4. Camila Cristina (Dairce Pedrosa - Altamira) -> Atendimento Regularizado (Verde)
  {
    id: 'a4444444-4444-4444-4444-444444444444',
    codigo: 'ALU-2026-004',
    nome: 'Camila Cristina Pinheiro',
    data_nascimento: '2011-02-14',
    sexo: 'F',
    endereco: 'Rua Magalhães Barata, 89 - Altamira',
    escola_id: 'e2222222-2222-2222-2222-222222222222',
    turma_id: 't-dairce-01',
    ciclo: 1,
    serie: '1º Ano Integral',
    situacao_doc: 'com_laudo',
    cid: 'F84.0',
    numero_processo: 'PROC-2026/0401-SEDUC',
    contrato_acompanhante: true,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: 'p-dairce-claudia',
    acompanhante_id: 'p-dairce-aldineia',
    observacoes: 'TEA em regime integral com apoio pedagógico e acompanhante regular.',
    ativo: true,
    created_by: 'u1111111-1111-1111-1111-111111111111',
    updated_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-10T14:00:00Z',
    updated_at: '2026-02-10T14:00:00Z',
  },

  // 5. Gabriel Silva Gomes (Getúlio Vargas - Altamira) -> Falta Acompanhante (Laranja)
  {
    id: 'a5555555-5555-5555-5555-555555555555',
    codigo: 'ALU-2026-005',
    nome: 'Gabriel Silva Gomes',
    data_nascimento: '2010-06-20',
    sexo: 'M',
    endereco: 'São Sebastião, Altamira',
    escola_id: 'e-alt-getulio',
    turma_id: null,
    ciclo: 2,
    serie: '2ª Série EM',
    situacao_doc: 'com_laudo',
    cid: 'G80 / F72',
    numero_processo: 'PROC-2025/1990-SEDUC',
    contrato_acompanhante: false,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: 'p-getulio-lucilene',
    acompanhante_id: null,
    observacoes: 'Deficiências múltiplas. Caso prioritário da unidade escolar; necessita de cuidador com urgência.',
    ativo: true,
    created_by: 'u1111111-1111-1111-1111-111111111111',
    updated_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-12T09:15:00Z',
    updated_at: '2026-02-16T11:40:00Z',
  },

  // 6. Aluno Surdo (Dom Pedro I - Porto de Moz) -> Falta Acompanhante / Intérprete (Laranja)
  {
    id: 'a6666666-6666-6666-6666-666666666666',
    codigo: 'ALU-2026-006',
    nome: 'Pedro Henrique Vasconcelos',
    data_nascimento: '2010-08-19',
    sexo: 'M',
    endereco: 'Rua Lauro Sodré, 45 - Porto de Moz',
    escola_id: 'e-pdm-pedro',
    turma_id: 't-pdm-01',
    ciclo: 2,
    serie: '2ª Série EM',
    situacao_doc: 'com_laudo',
    cid: 'H90.0',
    numero_processo: 'PROC-2025/2201-SEDUC',
    contrato_acompanhante: false,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: null,
    acompanhante_id: null,
    observacoes: 'Surdez bilateral profunda. Necessidade urgente de profissional intérprete de LIBRAS para mediação em sala regular.',
    ativo: true,
    created_by: 'u1111111-1111-1111-1111-111111111111',
    updated_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-14T10:00:00Z',
    updated_at: '2026-02-14T10:00:00Z',
  },

  // 7. Aluno Melvin Jones (Uruará) -> Falta Acompanhante (Laranja)
  {
    id: 'a7777777-7777-7777-7777-777777777777',
    codigo: 'ALU-2026-007',
    nome: 'Matheus Vinícius da Silva',
    data_nascimento: '2012-05-10',
    sexo: 'M',
    endereco: 'Av. Principal - Uruará',
    escola_id: 'e-uru-melvin',
    turma_id: 't-uru-01',
    ciclo: 1,
    serie: '8º Ano Regular',
    situacao_doc: 'com_laudo',
    cid: 'F84.0',
    numero_processo: 'PROC-2026/0991-SEDUC',
    contrato_acompanhante: false,
    necessita_professor_aee: true,
    necessita_acompanhante: true,
    professor_aee_id: 'p-uru-laurilene',
    acompanhante_id: null,
    observacoes: 'TEA com suporte pedagógico de AEE da Profª Laurilene, necessita acompanhante para apoio às atividades de vida diária.',
    ativo: true,
    created_by: 'u1111111-1111-1111-1111-111111111111',
    updated_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-20T11:30:00Z',
    updated_at: '2026-02-20T11:30:00Z',
  },

  // 8. Aluna Santa Clara (Anapu) -> Atendimento Regularizado (Verde)
  {
    id: 'a8888888-8888-8888-8888-888888888888',
    codigo: 'ALU-2026-008',
    nome: 'Vitória Emanuele Guzzo',
    data_nascimento: '2014-01-20',
    sexo: 'F',
    endereco: 'Rua Santa Luzia - Anapu',
    escola_id: 'e-anp-santaclara',
    turma_id: null,
    ciclo: 1,
    serie: '6º Ano Integral',
    situacao_doc: 'com_laudo',
    cid: 'Q90.9',
    numero_processo: 'PROC-2025/3340-SEDUC',
    contrato_acompanhante: true,
    necessita_professor_aee: false,
    necessita_acompanhante: true,
    professor_aee_id: null,
    acompanhante_id: 'p-anp-andreia',
    observacoes: 'Síndrome de Down com acompanhante Andreia Machado ativa em tempo integral.',
    ativo: true,
    created_by: 'u1111111-1111-1111-1111-111111111111',
    updated_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-22T08:00:00Z',
    updated_at: '2026-02-22T08:00:00Z',
  },
];

export const INITIAL_PDIS: PDI[] = [
  {
    id: 'd1111111-1111-1111-1111-111111111111',
    aluno_id: 'a1111111-1111-1111-1111-111111111111',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    ano_letivo: 2026,
    status: 'vigente',
    elaborado_por: 'Profª. Francilene de Menezes Silva',
    data_elaboracao: '2026-02-10',
    conteudo: {
      potencialidades: 'Excelente memória visual, interesse acentuado por artes visuais e informática, grande disciplina com cronogramas estruturados.',
      dificuldades: 'Hipersensibilidade auditiva, sobrecarga sensorial em transições de aulas e necessidade de mediação em interações coletivas.',
      objetivos_gerais: 'Garantir a permanência, o bem-estar socioemocional e a apropriação dos conteúdos curriculares da 3ª série do Ensino Médio.',
      objetivos_especificos: 'Desenvolver estratégias de autorregulação emocional; ampliar a participação oral com apoio de acompanhante.',
      estrategias_pedagogicas: 'Antecipação de rotinas semanais, uso de mapas mentais ilustrados, avaliações com tempo ampliado e permissão para abafador acústico.',
      recursos_acessibilidade: 'Abafador de ruído circum-auricular, prancha de comunicação alternativa e notebook adaptado.',
      metas_bimestre_1: 'Adaptação plena à rotina do terceirão e aos professores regentes.',
      metas_bimestre_2: 'Participação colaborativa em pequenos grupos com suporte de acompanhante.',
      metas_bimestre_3: 'Apresentação de trabalho interdisciplinar com mídia digital.',
      metas_bimestre_4: 'Consolidação das habilidades socioemocionais e preparação para o ENEM acessível.',
      avaliacao: 'O aluno apresentou avanços consistentes, demonstrando segurança na SRM e excelente entrosamento com a cuidadora Luana.',
    },
    created_by: 'u4444444-4444-4444-4444-444444444444',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'd4444444-4444-4444-4444-444444444444',
    aluno_id: 'a4444444-4444-4444-4444-444444444444',
    escola_id: 'e2222222-2222-2222-2222-222222222222',
    ano_letivo: 2026,
    status: 'vigente',
    elaborado_por: 'Profª. Cláudia Andrade da Silva',
    data_elaboracao: '2026-02-15',
    conteudo: {
      potencialidades: 'Comunicação verbal clara, criatividade e habilidade motora refinada para desenhos e modelagem.',
      dificuldades: 'Dificuldade de concentração prolongada em atividades puramente expositivas.',
      objetivos_gerais: 'Promover aprendizagem ativa integrada no regime integral.',
      objetivos_especificos: 'Fortalecer rotina de estudos nos turnos da manhã e tarde com a cuidadora Aldineia.',
      estrategias_pedagogicas: 'Segmentação de tarefas longas, pausas sensoriais dirigidas.',
      recursos_acessibilidade: 'Material impresso em fonte ampliada e jogos pedagógicos táteis.',
      metas_bimestre_1: 'Organização do cronograma de estudos integral.',
      metas_bimestre_2: 'Desenvolvimento de autonomia na alimentação e higiene.',
      metas_bimestre_3: 'Leitura compartilhada e interpretação textual.',
      metas_bimestre_4: 'Avaliação diagnóstica de encerramento do ciclo.',
      avaliacao: 'Evolução bastante positiva ao longo do primeiro mês letivo.',
    },
    created_by: 'u1111111-1111-1111-1111-111111111111',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
];

export const INITIAL_OFICIOS: Oficio[] = [
  {
    id: 'of-2026-001',
    ano: 2026,
    numero: 1,
    assunto: 'Solicitação Urgente de Profissionais de Apoio Escolar (Cuidadores) e Tradutor de LIBRAS — DRE Regional',
    destinatario: 'Diretoria de Educação Especial — SEDUC/PA',
    corpo: 'Cumprimentando-o cordialmente, vimos por meio deste encaminhar o levantamento consolidado das carências de Profissionais de Apoio Escolar (Cuidadores) e Intérprete de LIBRAS identificadas nas escolas estaduais da circunscrição regional, solicitando providências imediatas para suprimento das vagas.',
    status: 'emitido',
    escola_id: null,
    criado_por: 'u1111111-1111-1111-1111-111111111111',
    criado_por_nome: 'Prof. Dr. Valter Mendonça (Diretor do Núcleo)',
    emitido_em: '2026-02-18T14:00:00Z',
    alunos_ids: [
      'a2222222-2222-2222-2222-222222222222',
      'a3333333-3333-3333-3333-333333333333',
      'a5555555-5555-5555-5555-555555555555',
      'a6666666-6666-6666-6666-666666666666',
      'a7777777-7777-7777-7777-777777777777'
    ],
    created_at: '2026-02-18T11:00:00Z',
  },
];

export const INITIAL_DOCUMENTOS: DocumentoAluno[] = [
  {
    id: 'doc-001',
    aluno_id: 'a1111111-1111-1111-1111-111111111111',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    tipo: 'laudo',
    titulo: 'Laudo Neuropsiquiátrico - TEA CID F84.0',
    storage_path: 'documentos/laudo_gabriel_tea_2025.pdf',
    file_name: 'laudo_gabriel_tea_2025.pdf',
    tamanho_bytes: 1450000,
    enviado_por: 'Marcos Aurélio Lima',
    created_at: '2026-02-05T09:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-001',
    user_id: 'u1111111-1111-1111-1111-111111111111',
    user_nome: 'Prof. Dr. Valter Mendonça',
    usuario_nome: 'Prof. Dr. Valter Mendonça',
    usuario_papel: 'nucleo_diretor',
    acao: 'EMISSAO_OFICIO',
    tabela: 'oficios',
    entidade: 'oficios',
    registro_id: 'of-2026-001',
    detalhes: { numero: 1, ano: 2026, totalAlunos: 5 },
    created_at: '2026-02-18T14:00:00Z',
  },
];

export const INITIAL_ESTUDOS_DE_CASO: EstudoDeCaso[] = [
  {
    id: 'ec-001',
    aluno_id: 'a1111111-1111-1111-1111-111111111111',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    data_preenchimento: '2026-02-12',
    status: 'concluido',
    identificacao: {
      nome: 'Lucas Gabriel Ferreira dos Santos',
      data_nascimento: '2008-05-14',
      idade: 17,
      responsavel: 'Luciana Ferreira dos Santos (Mãe)',
      telefone: '(93) 98412-3301',
      endereco: 'Rua Sete de Setembro',
      numero: '450',
      bairro: 'Esplanada do Xingu',
      complemento: 'Próximo à Praça',
      cep: '68370-000',
      cidade: 'Altamira',
      estado: 'PA',
    },
    familia: {
      genitor: { nome: 'Carlos Eduardo dos Santos', profissao: 'Comerciante autônomo', telefone: '(93) 98412-3302', escolaridade: 'Ensino Médio Completo' },
      genitora: { nome: 'Luciana Ferreira dos Santos', profissao: 'Auxiliar Administrativa', telefone: '(93) 98412-3301', escolaridade: 'Ensino Superior Incompleto' },
    },
    escola_1_matricula: {
      nome_escola: 'EEE. M. Polivalente',
      endereco: 'Av. Brigadeiro Eduardo Gomes, s/n - Esplanada do Xingu',
      telefone_escola: '(93) 99108-0977',
      dre: 'DRE Altamira (Transamazônica)',
      diretor: 'Profª. Maria do Carmo Santos',
      telefone_diretor: '(93) 99108-0977',
      ano_etapa: '3ª Série do Ensino Médio',
      turma: '3ª Série EM - M01',
      turno: 'Matutino',
      quantitativo_estudantes: 34,
    },
    escola_2_aee: {
      nome: 'EEE. M. Polivalente - SRM',
      telefone: '(93) 99108-0977',
      endereco: 'Av. Brigadeiro Eduardo Gomes, s/n - Sala de Recursos Multifuncionais',
      ure_use: 'DRE Altamira',
      bairro: 'Esplanada do Xingu',
      municipio: 'Altamira',
      ano_ingresso: 2024,
      idade: 17,
      turma: 'SRM Contraturno AEE-01',
      turno: 'Vespertino',
      quantitativo_turma: 12,
    },
    historico_escolar: {
      antecedentes_relevantes: 'Estudante com diagnóstico de Transtorno do Espectro Autista (TEA nível 1 de suporte). Realizou o Ensino Fundamental em escola polo com suporte pedagógico. Apresenta ótimo engajamento com disciplinas de base visual e informática, porém necessita de mediação para regulação sensorial em ambientes ruidosos e na transição de professores.',
    },
    avaliacao_inicial: {
      deficiencia_intelectual: false,
      deficiencia_auditiva: '',
      surdez: false,
      surdez_faz_uso_libras: '',
      deficiencia_visual: '',
      surdocegueira: false,
      deficiencia_fisica: false,
      deficiencia_multipla: false,
      tea: true,
      altas_habilidades_superdotacao: false,
      dislexia: false,
      discalculia: false,
      disgrafia: false,
      tdah: false,
      tpac: false,
      tda: false,
      laudo_medico: 'sim',
      cid_laudo: 'F84.0',
      possui_problema_saude: 'sim',
      qual_problema_saude: 'Sensibilidade auditiva aumentada (hipersensibilidade acústica).',
      necessita_atencao_horario_escolar: 'sim',
      qual_atencao_necessita: 'Uso de fone abafador circum-auricular em momentos de recreio ou dinâmicas coletivas ruidosas.',
      faz_uso_medicacao: 'sim',
      qual_medicacao: 'Risperidona 1mg (uso noturno em domicílio)',
      horarios_medicacao: 'Às 21:00 em casa',
      tem_restricao_alimentar: 'nao',
    },
    aspectos_pedagogicos: {
      psicomotores: {
        praxia_global: 'sim',
        preensao_lapis: 'sim',
        dominancia_lateral: 'sim',
        dominancia_lateral_qual: 'Destro',
        lateralidade_dir_esq: 'sim',
        esquema_corporal: 'sim',
        coordenacao_visomotora: 'sim',
        complementares: 'Boa coordenação motora fina para desenho e digitação.',
      },
      linguagem_oral: {
        expressa_pela_fala: 'sim',
        fala_sem_omissao: 'sim',
        articula_palavras: 'sim',
        discriminacao_fonematica: 'sim',
        vocabulario_adequado: 'sim',
        compreensao_comandos: 'sim',
        expressa_pensamento_organizado: 'sim',
        faz_leitura: 'sim',
        nomeia_objetos_corretamente: 'sim',
        interpretacao_texto: 'sim',
        cria_historias: 'sim',
        uso_sinais: 'nao',
        complementares: 'Comunicação verbal formal bem desenvolvida. Por vezes literal no entendimento de metáforas.',
      },
      linguagem_escrita: {
        escrita_palavras_textos: 'sim',
        distincao_letras_numeros: 'sim',
        producao_textual_espontanea: 'sim',
        caligrafia_compreensivel: 'sim',
        escrita_espelhada: 'nao',
        pontuacao_acentuacao: 'sim',
        trocas: 'nao',
        inversoes: 'nao',
        omissoes: 'nao',
        aglutinacoes: 'nao',
        repeticao: 'nao',
        substituicao: 'nao',
        acrescimo: 'nao',
        organizacao_sintatica_semantica: 'sim',
        complementares: 'Produção textual fluida, com riqueza de vocabulário temático.',
      },
      raciocinio_matematico: {
        reconhecimento_numeros: 'sim',
        contagem: 'sim',
        calculos_sem_concreto: 'sim',
        formas_geometricas: 'sim',
        sequencia_fatos: 'sim',
        correlaciona_objetos_funcao: 'sim',
        complementares: 'Excelente raciocínio lógico em matemática e algoritmos computacionais.',
      },
      atencao_concentracao: {
        mantem_atencao: 'sim',
        distrai_se_nao_finaliza: 'nao',
        necessita_acompanhamento_continuo: 'nao',
        permanece_em_sala: 'sim',
        complementares: 'Mantém hiperfoco em temas de interesse. Necessita de aviso prévio antes da troca de atividades.',
      },
      sociabilidade_afetividade: {
        descricao: 'Tranquilo e afetuoso com colegas e professores. Não apresenta episódios de agressividade. Prefere interações em duplas a grandes grupos.',
      },
      vida_autonoma: {
        alimentacao_banheiro_autonomia: 'sim',
        identifica_perigo: 'sim',
        complementares: 'Total autonomia em atividades de vida diária no ambiente escolar.',
      },
    },
    apoios_saee: {
      professor_aee_contraturno: true,
      professor_bilingue: false,
      professor_libras: false,
      professor_portugues_surdos: false,
      tradutor_interprete_libras: false,
      guia_interprete: false,
      braillista: false,
      acompanhante_especializado: true,
    },
    plano_atendimento: {
      plano_aee: true,
      plano_aee_objetivo: 'Atendimento Educacional Especializado em SRM com foco em flexibilizações curriculares e suporte socioemocional.',
      plano_pei: true,
      plano_pei_objetivo: 'Elaboração e acompanhamento conjunto com os professores da 3ª série do Ensino Médio.',
      outros_encaminhamentos: false,
    },
    consideracoes_finais: {
      texto: 'O estudante é elegível para os apoios da Educação Especial (SRM e Acompanhante Especializado para mediação). Recomenda-se a formalização do PEI anual e acompanhamento semestral.',
      local: 'Altamira - PA',
      data: '2026-02-12',
      responsavel_nome: 'Profª. Francilene de Menezes Silva',
      responsavel_cargo: 'Professora de AEE - SRM',
      responsavel_matricula: 'MAT-584920-SEDUC',
    },
  },
];

export const INITIAL_PEIS: PEIOfficial[] = [
  {
    id: 'pei-001',
    aluno_id: 'a1111111-1111-1111-1111-111111111111',
    escola_id: 'e1111111-1111-1111-1111-111111111111',
    ano_letivo: 2026,
    status: 'vigente',
    data_elaboracao: '2026-02-15',
    periodo_execucao: 'Ano Letivo 2026 (1º e 2º Semestres)',
    identificacao: {
      nome: 'Lucas Gabriel Ferreira dos Santos',
      idade: 17,
      data_nascimento: '2008-05-14',
      ano_etapa: '3ª Série do Ensino Médio',
      turma: '3ª Série EM - M01',
      ano_ingresso: 2024,
      atendido_aee: 'sim',
      local_aee: 'srm',
    },
    indicadores: [
      {
        id: 'ind-1',
        problema_central: 'Sobrecarga sensorial e fadiga auditiva em ambientes escolares com ruído intenso.',
        causas: 'Hipersensibilidade auditiva característica do neurodesenvolvimento (TEA nível 1).',
        consequencias: 'Queda de rendimento e desconforto emocional em avaliações e aulas com múltiplos estímulos sonoros concorrentes.',
      },
      {
        id: 'ind-2',
        problema_central: 'Dificuldade na interpretação de enunciados com figuras de linguagem e metáforas abstratas.',
        causas: 'Pensamento pragmático e interpretação predominantemente literal.',
        consequencias: 'Necessidade de mediação pelo professor para compreensão plena de questões discursivas.',
      },
    ],
    contexto_familiar: {
      dados_responsaveis: 'Luciana Ferreira dos Santos (Mãe) e Carlos Eduardo dos Santos (Pai). Família participativa e colaborativa com a equipe pedagógica.',
      historico_vida: 'Diagnóstico precoce aos 4 anos. Histórico de estimulação multidisciplinar e boa adaptação à rotina escolar ao longo do ciclo básico.',
      expectativa_familiar: 'Conclusão bem-sucedida do Ensino Médio com aprovação no Exame Nacional do Ensino Médio (ENEM) e ingresso no Ensino Superior na área de Tecnologia da Informação.',
    },
    areas_desenvolvimento: {
      percepcao: 'Excelente percepção visual e espacial. Sensibilidade a estímulos acústicos intensos.',
      atencao_concentracao: 'Capacidade de atenção concentrada sustentada em temas de interesse; necessita de pausas programadas durante provas longas.',
      memoria: 'Memória visual e sequencial acima da média para datas, padrões e fórmulas.',
      linguagem: 'Comunicação verbal bem estruturada na oralidade e escrita; interpretação com mediação para linguagem figurada.',
      raciocinio_logico: 'Domínio consolidado de lógica matemática, cálculos e resolução de problemas estruturados.',
      aspectos_psicomotores: 'Adequados para a faixa etária. Boa coordenação motora fina.',
      atividade_vida_autonoma: 'Total independência para locomoção, uso do banheiro, alimentação e cuidado com materiais pessoais.',
      aspectos_interpessoais_sociais: 'Relacionamento cordial e respeitoso com professores e colegas. Busca espaços mais tranquilos durante o recreio.',
    },
    ensino_individualizado: {
      objetivos_aprendizagem: 'Garantir a apropriação dos conteúdos da 3ª série do EM de acordo com a BNCC; desenvolver estratégias de autorregulação e resolução de questões do ENEM.',
      avaliacao_aprendizagem: 'Tempo estendido (+1 hora) para avaliações escritas; aplicação em ambiente com menor nível de ruído; enunciados claros com mediação de dúvidas de interpretação.',
      tipos_apoio: 'Atendimento na SRM no contraturno (2 vezes semanais); acompanhante de mediação em sala regular; autorização para uso de fone abafador.',
      projeto_vida: 'Aprofundamento nas áreas de Ciências Exatas e Computação; oficinas preparatórias para o ENEM e orientação vocacional para curso de Sistemas de Informação na UFPA.',
    },
    assinaturas: {
      local: 'Altamira - PA',
      data: '2026-02-15',
      professor_saee: 'Profª. Francilene de Menezes Silva (AEE)',
      responsavel_pedagogico: 'Prof. Antonio Vieira Bispo (Coordenação Pedagógica)',
      professores_turma: [
        'Prof. Marcos Vinicius (Língua Portuguesa)',
        'Profª. Sandra Regina (Matemática)',
      ],
    },
  },
];
